# Generated by Django 5.0.8 on 2024-10-22 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='Shop name')),
                ('item_description', models.TextField(verbose_name='Item description')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total cost')),
                ('initial_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Initial payment')),
                ('payment_frequency', models.CharField(choices=[('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], max_length=10, verbose_name='Frequency')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('expected_end_date', models.DateField(verbose_name='Expected end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Is complete')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laybys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Layby',
                'verbose_name_plural': 'Laybys',
                'ordering': ['-start_date'],
            },
        ),
    ]
