# Generated by Django 5.0.8 on 2024-10-22 09:43

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laybys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layby',
            name='initial_payment',
        ),
        migrations.AlterField(
            model_name='layby',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the layby is currently active', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='layby',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='Indicates if all payments have been made', verbose_name='Is complete'),
        ),
        migrations.AlterField(
            model_name='layby',
            name='payment_frequency',
            field=models.CharField(choices=[('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10, verbose_name='Payment frequency'),
        ),
        migrations.AlterField(
            model_name='layby',
            name='shop_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Shop name'),
        ),
        migrations.AlterField(
            model_name='layby',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 22, 9, 43, 55, 840894, tzinfo=datetime.timezone.utc), verbose_name='Start date'),
        ),
        migrations.AddIndex(
            model_name='layby',
            index=models.Index(fields=['-start_date', 'user'], name='laybys_layb_start_d_4eb2d0_idx'),
        ),
    ]
